<?php
/**
 * topmenu.phtml
 *
 * @Date        09/2017
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 * @author      @diazwatson
 */

declare(strict_types=1);

/** @var \Space48\CmsMenu\Block\Html\CmsTopmenu $block */
$categories = $block->getStoreCategories(true);
?>
<div class="nav__wrapper">
    <nav class="nav">
        <ul class="clearfix">
            <?php foreach ($categories as $category) : ?>
                <li class="nav__top-level nav__parent">
                    <a href="<?php echo $block->getCategoryUrl($category); ?>"><?php echo $category->getData('name'); ?></a>
                    <?php if ($block->getCmsMenu($category)) : ?>
                        <div class="nav__dropdown">
                            <div class="wrapper">
                                <div class="nav__column">
                                    <?php echo $block->getCmsMenu($category); ?>
                                </div>
                            </div>
                        </div>
                    <?php endif; ?>
                </li>
            <?php endforeach; ?>
        </ul>
    </nav>
</div>
<script type="text/x-magento-init">
    {
        ".nav__wrapper": {
            "navigation": {}
        }
    }


</script>
