<?php
/**
 * Space48_CmsMenu
 *
 * @category    Space48
 * @package     Space48_CmsMenu
 * @Date        09/2017
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 * @author      @diazwatson
 */

declare(strict_types=1);

/** @var \Space48\CmsMenu\Block\Html\TopMenu $block */
$categories = $block->getStoreCategories(true);
$itemCount = 0;
?>
<nav class="navigation">
    <ul data-mage-init='{"menu":{"responsive":true, "expanded":true, "position":{"my":"left top","at":"left bottom"}}}'>
        <?php foreach ($categories as $category) : ?>
            <li class="level0 nav-<?= $block->escapeHtml($itemCount++) ?> first level-top ui-menu-item">
                <a href="<?php echo $block->escapeUrl($block->getCategoryUrl($category)); ?>" class="level-top ui-corner-all">
                    <?php echo $block->escapeHtml($category->getData('name')); ?>
                </a>
                <?php if ($cmsMenu = $block->getCmsMenu($category)) : ?>
                    <ul class="level0 submenu ui-menu ui-widget ui-widget-content ui-corner-all">
                        <?php echo $block->escapeHtml($cmsMenu); ?>
                    </ul>
                <?php endif; ?>
            </li>
        <?php endforeach; ?>
    </ul>
</nav>
